# Generated by Django 6.1.1 on 2026-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerapplication',
            name='recommended_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
