# Generated by Django 6.1.1 on 2026-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_cycle', '0002_alter_fertilizerapplication_recommended_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerapplication',
            name='nutrients',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fertilizerapplication',
            name='stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerapplication',
            name='fertilizer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
